-- -- 2️⃣ Kullanıcılar
-- INSERT INTO user_tbl (pass_word, email, phone, usercode, first_name, last_name) VALUES
-- ('hashedpassword1', 'john@example.com', '1234567890', 1, 'John', 'Doe'),
-- ('hashedpassword2', 'admin@example.com', '0987654321', 2, 'Admin', 'User');

-- -- 3️⃣ Kullanıcı adresleri
-- INSERT INTO user_address (user_id, address, city, postal_code, country) VALUES
-- (1, '123 Main St', 'Anytown', '12345', 'USA'),
-- (2, '456 Admin Ave', 'Admin City', '67890', 'USA');

-- 4️⃣ Kategoriler
INSERT INTO category_table (category_name) VALUES
('Perfume'),
('Room Fragrance and Candles'),
('Sunscreen'),
('Moisturizer'),
('Serum'),
('Lipstick'),
('Foundation'),
('Mascara'),
('Concealer'),
('Eyeshadow'),
('Powder'),
('Body Lotion');

-- 5️⃣ Ürünler
INSERT INTO product ( product_name, description, price, category_id, stock) VALUES
('BLEU DE CHANEL', '50ml. A woody and aromatic scent reflecting masculine elegance, a fresh yet deep perfume for modern and confident men, destined to become their signature fragrance.', 4400.00, 1, 20),
('Frédéric Malle Portrait of a Lady', '100ml. A sophisticated yet dizzying expression of passion, featuring intense rose and patchouli notes.', 16950.00, 1, 20),
('Byredo Mojave Ghost', '100ml. A delicate and mysterious scent that reflects the spirit of the desert, a light woody and floral unisex perfume suitable for both men and women.', 12840.00, 1, 10),
('Maison Francis Kurkdjian Baccarat Rouge', '70ml. A mesmerizing and striking unisex perfume with amber, jasmine, and saffron notes, leaving a warm, sugary, and crystalline trail.', 13230.00, 1, 20),
('Creed Aventus for Her', '75ml. Opening with pineapple, green apple, and musk, this fresh and fruity fragrance reflects the confident stance of strong yet elegant women.', 16750.00, 1, 20),
('Diptyque Philosykos', '100ml. A refreshing unisex scent that captures the Mediterranean spirit with fresh fig, fig leaves, and woody notes.', 7450.00, 1, 10),
('Parfums de Marly Delina', '75ml. A sweet, floral, and fresh women’s perfume featuring Turkish rose, lychee, and musk, blending femininity with elegance.', 13110.00, 1, 10),
('Yves Saint Laurent Libre', '90ml. A modern and bold fragrance for free-spirited women, blending powerful lavender with orange blossom, creating a fresh yet deep scent.', 7600.00, 1, 30),
('Kilian Paris Rolling In Love', '50ml. A luxurious and intense women’s perfume leaving a warm, sweet, and romantic trail with almond, vanilla, and iris notes.', 10500.00, 1, 10),
('Tom Ford Tobacco Vanille', '100ml. A perfect winter fragrance with rich tobacco and vanilla notes, creating a warm, sweet, spicy, and masculine effect.', 14870.00, 1, 10),
('Jo Malone London Velvet Rose & Oud', '165ml. A home fragrance that creates a warm, luxurious, and mysterious atmosphere with rich rose and intense woody oud notes—ideal for elegant and sophisticated spaces.', 4920.00, 2, 15),
('Atelier Rebul İstanbul Xl Scented Candle', '950g. A large scented candle reflecting Istanbul’s mystical spirit with bergamot, spices, and woody notes, adding a warm and luxurious atmosphere.', 5200.00, 2, 15),
('FEU DE CIEL Kalp Çakra', '130g. A handmade natural candle featuring rose notes, aiming to balance the heart chakra and support emotional release and inner peace.', 949.90, 2, 15),
('Charya Maison Mystic Amber', '230g. A natural and vegan scented candle that creates a deep and sophisticated atmosphere with the warm tones of amber and sandalwood.', 750.00, 2, 15),
('Atelier Rebul Saffron Oud', '200ml. A luxurious room scent that opens with carrot and cinnamon, enriched with saffron, incense, and leather, and deepened with patchouli and sandalwood, creating a sophisticated and spicy ambiance.', 1700.00, 2, 15),
('Jo Malone London English Pear & Freesia', '165ml. A fresh, elegant, and sophisticated home fragrance blending ripe pear and white freesia with amber and patchouli.', 3950.00, 2, 15),
('Yankee Candle Amber & Sandalwood', '567g. A sweet and spicy scented candle that creates a sophisticated and relaxing ambiance with the combination of woody sandalwood and warm amber.', 1799.00, 2, 1),
('Shiseido Clear Suncare Stick', 'SPF 50+. A light and water-resistant sunscreen stick that provides high protection without leaving a white cast.', 2790.00, 3, 10),
('Beauty Of Joseon Matte Mugwort + Camelia', 'SPF 50+ PA++++. A practical, skin-friendly sunscreen stick that offers high protection with a matte finish and a light, oil-free appearance.', 1019.00, 3, 10),
('La Roche Posay Anthelios İnvisible Fluid', 'SPF 50+. A lightweight, water-resistant sunscreen fluid that provides high UV protection without leaving marks on the skin.', 687.06, 3, 10),
('LANCÔME UV Expert Youth Shield Milky Bright', 'SPF 50+. A sunscreen cream offering broad-spectrum protection, evening out skin tone while hydrating and helping to maintain a youthful appearance.', 2800.00, 3, 10),
('SISLEY Super Soin Solitaire Youth', 'SPF 30. A sun care product that protects the skin from UV rays while providing anti-aging benefits to maintain a youthful and healthy look.', 7780.00, 3, 10),
('CLINIQUE Moisture Surge Sheertint Hydrator', 'SPF 25. A skincare product with a lightweight tinted texture that moisturizes the skin while providing UV protection and a natural glow.', 1600.00, 3, 10),
('LANCASTER Sun Perfect Unifying Serum', 'SPF 50. A lightweight and hydrating serum that provides high UV protection while evening skin tone and reducing the appearance of dark spots.', 2560.00, 3, 10),
('SUPERGOOP! Glowscreen', 'SPF 30 PA+++. A sunscreen that hydrates and illuminates the skin with hyaluronic acid and niacinamide, offering a radiant finish with sun protection.', 2899.00, 3, 10),
('LA MER The Radiant Skintint', 'SPF 30. A lightweight, hydrating tinted moisturizer that evens skin tone, adds a natural glow, and provides sun protection.', 4510.00, 3, 10),
('DIOR Dreamskin Moist & Perfect Cushion', 'SPF 50 - PA+++. A makeup and skincare hybrid product that evens skin tone, reduces pores, offers anti-aging benefits, and provides high sun protection with a natural, matte glow.', 3795.00, 3, 10),
('GLOW RECIPE Plum Plump', '20ml. A lightweight, oil-free gel cream that deeply hydrates and plumps the skin using Kakadu plum and multi-molecular hyaluronic acid.', 1420.00, 4, 15),
('THE ORDINARY Natural Moisturizing Factors', '30ml. A lightweight, oil-free moisturizer containing amino acids, hyaluronic acid, and ceramides that support the skin’s natural moisture barrier.', 295.00, 4, 15),
('CLINIQUE Moisture Surge™', '30ml. An oil-free gel cream that hydrates the skin in 3 seconds and locks in moisture for up to 100 hours with aloe bioferment and hyaluronic acid.', 1025.00, 4, 15),
('BYOMA Moisturizing Gel Cream', '50ml. A lightweight, oil-free gel cream that strengthens the skin barrier and hydrates with Tri-Ceramide Complex, niacinamide, and green tea extract.', 1089.00, 4, 15),
('LA MER Moisturizing Cream', '30ml. A luxurious cream enriched with Miracle Broth™ from the sea that deeply hydrates, soothes, and reduces the appearance of fine lines and wrinkles for a youthful glow.', 9260.00, 4, 15),
('Bioderma Atoderm Ultra', '500ml. A lightweight, non-comedogenic cream suitable for face and body, offering 24-hour hydration and nourishment with glycerin, niacinamide, and omega 3-6-9 for dry and sensitive skin of all ages.', 845.00, 4, 15),
('cream co. Moisturizer', '50ml. A lightweight, water-based facial moisturizer that deeply hydrates and brightens the skin with five types of hyaluronic acid, niacinamide, and panthenol.', 291.00, 4, 15),
('IS Clinical Youth Intensive Creme', 'A luxurious anti-aging cream with hyaluronic acid, vitamin C, and copper tripeptide that provides 24-hour deep hydration and reduces the appearance of fine lines and wrinkles.', 15988.50, 4, 15),
('Aveda Stress Fix Body Lotion', '200ml. A relaxing body lotion formulated with organic lavender and sage extracts that moisturizes the skin while helping to reduce the feeling of stress.', 2810.00, 4, 15),
('Janssen Cosmetics Moisturizing Cream', '50ml. A lightweight, fast-absorbing cream specially formulated for dry and dehydrated skin, deeply moisturizes and nourishes.', 1460.00, 4, 15),
('THE ORDINARY Hyaluronic Acid 2% + B5', '30ml. A lightweight, oil-free serum that deeply hydrates and plumps the skin while strengthening the skin barrier and reducing water loss with vitamin B5.', 398.90, 5, 20),
('ESTÉE LAUDER Advanced Night Repair', '30ml. An anti-aging night serum known for its repairing effects, contains hyaluronic acid and Chronolux™ Power Signal Technology to support skin repair overnight.', 3850.00, 5, 20),
('GLOW RECIPE Watermelon Glow Dew Drops', '15ml. A radiant serum that instantly adds glow to the skin with niacinamide and watermelon extract. It contains no mica, glitter, or pearls for a natural glow.', 1340.00, 5, 20),
('CLINIQUE Moisture Surge Active Glow', '30ml. Provides deep hydration and an instant glow while being fragrance-free, allergy-tested, and suitable for all skin types, including sensitive skin.', 1990.00, 5, 20),
('DIOR Capture Totale Super Potent Eye Serum', '20ml. Targets 9 signs of aging around the eyes, provides instant glow and firming effect with a 360° Cryo-Flex applicator, visibly rejuvenates eye area in 4 weeks.', 5110.00, 5, 20),
('LANCÔME Rénergie Triple Serum', '50ml. A triple-effect anti-aging serum that evens out skin tone, reduces the appearance of wrinkles, and instantly boosts radiance.', 7250.00, 5, 20),
('La Roche Posay Hyalu B5', '30ml. Deeply hydrates the skin with two types of hyaluronic acid and vitamin B5, reduces the appearance of wrinkles and leaves the skin plump and firm.', 2166.00, 5, 20),
('Clarins Double Serum Light Texture', '50ml. Moisturizes the skin while reducing the appearance of fine lines, resulting in firmer and more radiant skin.', 5480.00, 5, 20),
('Lumene Moisturizing Prebiotic Oil Coctail', '30ml. Supports the skin’s moisture barrier, provides intense hydration for 24 hours, and is specially formulated for dry skin.', 1100.00, 5, 20),
('Anua Niacinamide 10% + TXA 4%', '30ml. Evens out skin tone, reduces the appearance of spots, tightens pores, and gives the skin a radiant glow.', 1235.20, 5, 20),
('Yves Saint Laurent Loveshine RVS 202', 'A lipstick that provides up to 24-hour hydration and shine with nourishing oils and a lightweight, comfortable texture.', 1960.00, 6, 15),
('Yves Saint Laurent Loveshine RVS 212', 'A lipstick that provides up to 24-hour hydration and shine with nourishing oils and a lightweight, comfortable texture.', 1960.00, 6, 15),
('Yves Saint Laurent Loveshine RVS 209', 'A lipstick that provides up to 24-hour hydration and shine with nourishing oils and a lightweight, comfortable texture.', 1960.00, 6, 15),
('DIOR Rouge Dior 777', 'Enriched with floral extracts, this lipstick offers 24-hour hydration and comfort, available in finishes like velvet matte, satin, and the new "new veil".', 2215.00, 6, 15),
('DIOR Rouge Dior 028', 'Enriched with floral extracts, this lipstick offers 24-hour hydration and comfort, available in finishes like velvet matte, satin, and the new "new veil".', 2215.00, 6, 15),
('DIOR Rouge Dior 080', 'Enriched with floral extracts, this lipstick offers 24-hour hydration and comfort, available in finishes like velvet matte, satin, and the new "new veil".', 2215.00, 6, 15),
('FENTY BEAUTY Fenty Icon 01', 'With rich pigmentation, a moisturizing formula, and sleek design, it delivers long-lasting vibrant color to the lips.', 1269.00, 6, 15),
('FENTY BEAUTY Fenty Icon 02', 'With rich pigmentation, a moisturizing formula, and sleek design, it delivers long-lasting vibrant color to the lips.', 1269.00, 6, 15),
('FENTY BEAUTY Fenty Icon 03', 'With rich pigmentation, a moisturizing formula, and sleek design, it delivers long-lasting vibrant color to the lips.', 1269.00, 6, 15),
('GUERLAIN ROUGE G 968', 'With a 89% skincare-based formula, it hydrates and plumps the lips while offering a luxurious makeup experience with elegant packaging and rich color options.', 2405.00, 6, 150),
('GUERLAIN ROUGE G 879', 'With a 89% skincare-based formula, it hydrates and plumps the lips while offering a luxurious makeup experience with elegant packaging and rich color options.', 2405.00, 6, 150),
('GUERLAIN ROUGE G 880', 'With a 89% skincare-based formula, it hydrates and plumps the lips while offering a luxurious makeup experience with elegant packaging and rich color options.', 2405.00, 6, 150),
('CHARLOTTE TILBURY Look of Love Mrs Kisses', 'The lipstick collection provides long-lasting hydration and vibrant color, delivering a natural and radiant look.', 2089.00, 6, 15),
('CHARLOTTE TILBURY Look of Love Wedding Belles', 'The lipstick collection provides long-lasting hydration and vibrant color, delivering a natural and radiant look.', 2089.00, 6, 15),
('CHARLOTTE TILBURY Look of Love First Dance', 'The lipstick collection provides long-lasting hydration and vibrant color, delivering a natural and radiant look.', 2089.00, 6, 15),
('VALENTINO Spike Valentino 111A', 'Provides comfortable and long-lasting matte color for up to 10 hours, enriched with cottonseed oil to nourish lips and delivers a luxurious experience with its iconic golden brass packaging.', 2579.00, 6, 15),
('VALENTINO Spike Valentino 508R', 'Provides comfortable and long-lasting matte color for up to 10 hours, enriched with cottonseed oil to nourish lips and delivers a luxurious experience with its iconic golden brass packaging.', 2579.00, 6, 15),
('VALENTINO Spike Valentino 77A', 'Provides comfortable and long-lasting matte color for up to 10 hours, enriched with cottonseed oil to nourish lips and delivers a luxurious experience with its iconic golden brass packaging.', 2579.00, 6, 15),
('ARMANI Luminous Silk 6', '30ml. With a silky texture and medium coverage, it gives the skin a natural glow and a flawless look that lasts all day.', 3070.00, 7, 10),
('ARMANI Luminous Silk 8', '30ml. With a silky texture and medium coverage, it gives the skin a natural glow and a flawless look that lasts all day.', 3070.00, 7, 10),
('ARMANI Luminous Silk 1.5', '30ml. With a silky texture and medium coverage, it gives the skin a natural glow and a flawless look that lasts all day.', 3070.00, 7, 10),
('DIOR BACKSTAGE Face & Body Foundation 2N', 'A long-lasting foundation with an ultra-fine texture and 94% natural-origin ingredients, providing a natural, radiant finish. Water- and sweat-resistant.', 2080.00, 7, 10),
('DIOR BACKSTAGE Face & Body Foundation 10N', 'A long-lasting foundation with an ultra-fine texture and 94% natural-origin ingredients, providing a natural, radiant finish. Water- and sweat-resistant.', 2080.00, 7, 10),
('DIOR BACKSTAGE Face & Body Foundation 2CR', 'A long-lasting foundation with an ultra-fine texture and 94% natural-origin ingredients, providing a natural, radiant finish. Water- and sweat-resistant.', 2080.00, 7, 10),
('MAKEUP BY MARIO SurrealSkin™ Foundation 4C', '30ml. A breathable formula with a radiant finish, offering medium coverage and long-lasting wear. Enriched with hydrating ingredients for a nourished feel and all-day comfort.', 2649.00, 7, 10),
('MAKEUP BY MARIO SurrealSkin™ Foundation 11N', '30ml. A breathable formula with a radiant finish, offering medium coverage and long-lasting wear. Enriched with hydrating ingredients for a nourished feel and all-day comfort.', 2649.00, 7, 10),
('MAKEUP BY MARIO SurrealSkin™ Foundation 30W', '30ml. A breathable formula with a radiant finish, offering medium coverage and long-lasting wear. Enriched with hydrating ingredients for a nourished feel and all-day comfort.', 2649.00, 7, 10),
('NARS Light Reflecting Foundation Oslo', '30ml. A hybrid makeup-skincare formula that delivers buildable medium coverage with a radiant finish. Instantly blurs imperfections and visibly improves skin clarity over time with regular use.', 2485.00, 7, 10),
('NARS Light Reflecting Foundation Macao', '30ml. A hybrid makeup-skincare formula that delivers buildable medium coverage with a radiant finish. Instantly blurs imperfections and visibly improves skin clarity over time with regular use.', 2485.00, 7, 10),
('NARS Light Reflecting Foundation Lima', '30ml. A hybrid makeup-skincare formula that delivers buildable medium coverage with a radiant finish. Instantly blurs imperfections and visibly improves skin clarity over time with regular use.', 2485.00, 7, 10),
('CHANEL LES BEIGES WATER FRESH Complexion Touch B80', '30ml. An ultra-light complexion product with 75% water content and micro-droplet technology, delivering a fresh, dewy, and natural glow to the skin.', 2800.00, 7, 10),
('CHANEL LES BEIGES Foundation B10', '30ml. An ultra-light complexion product with 75% water content and micro-droplet technology, delivering a fresh, dewy, and natural glow to the skin.', 2800.00, 7, 10),
('CHANEL LES BEIGES Foundation B20', '30ml. An ultra-light complexion product with 75% water content and micro-droplet technology, delivering a fresh, dewy, and natural glow to the skin.', 2800.00, 7, 10),
('LANCÔME Teint Idole Ultra Wear 315C', 'A high-coverage foundation offering a matte finish and lightweight feel, providing a natural look that lasts for 24 hours.', 2695.00, 7, 10),
('LANCÔME Teint Idole Ultra Wear 425C', 'A high-coverage foundation offering a matte finish and lightweight feel, providing a natural look that lasts for 24 hours.', 2695.00, 7, 10),
('LANCÔME Teint Idole Ultra Wear 105W', 'A high-coverage foundation offering a matte finish and lightweight feel, providing a natural look that lasts for 24 hours.', 2695.00, 7, 10),
('Charlotte Tilbury Pillow Talk Push Up Lashes Dream Pop', 'A plum-brown mascara that instantly lifts, lengthens, and volumizes lashes, offering a 24-hour vertical lift effect while enhancing eye color.', 1919.00, 8, 15),
('Charlotte Tilbury Pillow Talk Push Up Lashes Super Black', 'An intense black mascara that provides instant volume, length, and a 24-hour vertical lift effect for dramatic lashes.', 1919.00, 8, 15),
('Yves Saint Laurent Lash Clash', 'A long-lasting mascara that adds extra volume and intense black color to the lashes, giving a dramatic and bold look.', 2200.00, 8, 15),
('Yves Saint Laurent Mascara Lash Clash 02 Brun', 'A mascara that instantly adds up to 200% more volume with a long-lasting formula in deep brown, lasting 24 hours.', 2200.0, 8, 15),
('BENEFIT COSMETICS BADgal Bounce', 'A mascara that lifts lashes from root to tip with intense volume and provides a dramatic look with its flexible formula that lasts all day.', 1809.00, 8, 15),
('LANCÔME Cils Booster Lash Serum', 'A serum enriched with amino acids to nourish and strengthen lashes from root to tip, reducing fallouts during makeup removal.', 2550.00, 8, 15),
('LANCÔME Lash Idôle', 'A mascara that instantly provides volume, length, and lift for up to 24 hours with a non-clumping and lightweight formula.', 1750.00, 8, 15),
('FENTY BEAUTY Hella Thicc Volumizing Mascara', 'An ultra-creamy formula with a narrow wand that delivers intense volume, length, and lift, providing a dramatic look resistant to sweat, humidity, and smudging.', 599.00, 8, 15),
('ARMANI Vertigo Lift', 'A mascara that gives intense volume and dramatic length for bold and lifted lashes; non-smudging and non-clumping for up to 24 hours.', 2250.00, 8, 15),
('ESTÉE LAUDER Sumptuous Extreme', 'A mascara that provides dramatic volume, lift, and length for a false-lash effect, staying in place all day with its special formula.', 1890.00, 8, 15),
('NARS Climax Extreme', 'A mascara that delivers dramatic volume and deep black pigment with just one coat, giving striking lashes.', 1490.00, 8, 15),
('TARTE Tartelette™ Tubing', 'A mascara that adds volume, length, and lift to lashes, resistant to clumping and smudging for 24 hours, easily removed with warm water.', 1689.00, 8, 15),
('RARE BEAUTY Perfect Strokes Universal', 'A mascara that nourishes, volumizes, lengthens, and curls lashes without clumping, providing a natural look. The formula with castor oil keeps lashes soft and offers long-lasting wear.', 1379.00, 8, 15),
('ARMANI Luminous Silk 4.75', 'A silky-textured foundation with medium coverage that gives a natural radiant finish, providing a flawless look that lasts all day.', 2400.00, 9, 10),
('ARMANI Luminous Silk 5.00', 'A silky-textured foundation with medium coverage that gives a natural radiant finish, providing a flawless look that lasts all day.', 2400.00, 9, 10),
('ARMANI Luminous Silk 7.5', 'A silky-textured foundation with medium coverage that gives a natural radiant finish, providing a flawless look that lasts all day.', 2400.00, 9, 10),
('Yves Saint Laurent All Hours LC5', 'A foundation with 24-hour wear, full coverage, and a lightweight formula that delivers a flawless, natural matte finish.', 2300.00, 9, 10),
('Yves Saint Laurent All Hours LN1', 'A foundation with 24-hour wear, full coverage, and a lightweight formula that delivers a flawless, natural matte finish.', 2300.00, 9, 10),
('Yves Saint Laurent All Hours MW2', 'A foundation with 24-hour wear, full coverage, and a lightweight formula that delivers a flawless, natural matte finish.', 2300.00, 9, 10),
('TARTE Shape Tape™ Radiant Concealer 22N', 'With medium coverage and a radiant finish, this concealer gives the skin a natural glow, provides 24-hour hydration with a triple hyaluronic acid blend, and brightens dark circles with a photo-luminescent complex.', 1759.00, 9, 10),
('TARTE Shape Tape™ Radiant Concealer 38N', 'With medium coverage and a radiant finish, this concealer gives the skin a natural glow, provides 24-hour hydration with a triple hyaluronic acid blend, and brightens dark circles with a photo-luminescent complex.', 1759.00, 9, 10),
('TARTE Shape Tape™ Radiant Concealer 57N', 'With medium coverage and a radiant finish, this concealer gives the skin a natural glow, provides 24-hour hydration with a triple hyaluronic acid blend, and brightens dark circles with a photo-luminescent complex.', 1759.00, 9, 10),
('TOO FACED Born This Way Super Coverage Concealer Vanilla', 'A versatile concealer with full coverage and 12-hour wear, ideal for concealing under-eye circles, evening out skin tone, contouring, and highlighting. Its lightweight, oil-free formula is enriched with coconut water, alpine rose, and hyaluronic acid to hydrate the skin and provide a natural finish.', 1759.00, 9, 10),
('TOO FACED Born This Way Super Coverage Concealer Latte', 'A versatile concealer with full coverage and 12-hour wear, ideal for concealing under-eye circles, evening out skin tone, contouring, and highlighting. Its lightweight, oil-free formula is enriched with coconut water, alpine rose, and hyaluronic acid to hydrate the skin and provide a natural finish.', 1759.00, 9, 10),
('TOO FACED Born This Way Super Coverage Concealer Toffee', 'A versatile concealer with full coverage and 12-hour wear, ideal for concealing under-eye circles, evening out skin tone, contouring, and highlighting. Its lightweight, oil-free formula is enriched with coconut water, alpine rose, and hyaluronic acid to hydrate the skin and provide a natural finish.', 1759.00, 9, 10),
('DIOR BACKSTAGE Concealer 2N', 'With high coverage, a water-resistant and non-caking formula, this concealer covers skin imperfections while providing a natural radiant finish. Infused with caffeine, it revives the eye area, and the special brush applicator allows precise application.', 1445.00, 9, 10),
('DIOR BACKSTAGE Concealer 4W', 'With high coverage, a water-resistant and non-caking formula, this concealer covers skin imperfections while providing a natural radiant finish. Infused with caffeine, it revives the eye area, and the special brush applicator allows precise application.', 1445.00, 9, 10),
('DIOR BACKSTAGE Concealer 9N', 'With high coverage, a water-resistant and non-caking formula, this concealer covers skin imperfections while providing a natural radiant finish. Infused with caffeine, it revives the eye area, and the special brush applicator allows precise application.', 1445.00, 9, 10),
('NATASHA DENONA Hy-Glam Concealer YP3', 'With medium to full coverage and a serum-like lightweight texture, this concealer brightens under-eye circles while providing a natural and radiant finish with its wide 50-shade range.', 1839, 9, 10),
('NATASHA DENONA Hy-Glam Concealer P3', 'With medium to full coverage and a serum-like lightweight texture, this concealer brightens under-eye circles while providing a natural and radiant finish with its wide 50-shade range.', 1839, 9, 10),
('NATASHA DENONA Hy-Glam Concealer RN9', 'With medium to full coverage and a serum-like lightweight texture, this concealer brightens under-eye circles while providing a natural and radiant finish with its wide 50-shade range.', 1839, 9, 10),
('MAKEUP BY MARIO Master Mattes® Eyeshadow Palette', 'A palette featuring 12 universal matte shades inspired by human skin tones, offering a lightweight, creamy formula that blends and layers easily for a natural, professional eye makeup look.', 3459.00, 10, 20),
('HUDA BEAUTY Icy Nude Eyeshadow Palette', 'A palette with 18 ultra-pigmented shades in various textures, ranging from mattes to shimmering glitters, adding a sophisticated and frosty touch to your eye makeup. Designed in cool-toned nudes, grays, and pinks, it is ideal for cooler undertones. Offers high pigmentation, smooth blendability, and long-lasting wear.', 3939.00, 10, 10),
('TOO FACED Born This Way The Natural Nudes', 'Featuring 16 highly pigmented matte, metallic, and radiant shades inspired by true skin tones, this palette provides natural yet stunning eye makeup looks.', 3139.00, 10, 10),
('NATASHA DENONA I Need a Warm', 'A palette with 15 rich shades in champagne, caramel, copper, and warm coffee tones, offering natural yet impactful eye makeup looks. The new "Slip Cream Matte" formula blends creamy mattes and shimmering metallic textures easily, providing long-lasting wear.', 3939.00, 10, 10),
('Chiara Ferragni Multicolor Eyeshadow Palette', 'A fun palette with vibrant and shimmering shades designed for both everyday and bold makeup looks, made with high-pigmented eyeshadows.', 5425.00, 10, 10),
('ANASTASIA BEVERLY HILLS Soft Glam', 'With 9 ultra-matte and 5 metallic shades, this palette offers 14 rich colors perfect for soft and radiant eye makeup looks from day to night.', 3329.00, 10, 10),
('TARTE Tartelette™ In Bloom Clay Palette', 'A palette with 9 matte and 3 shimmery tones, offering 12 neutral and warm shades that are perfect for any makeup style from day to night, made with Amazonian clay for long-lasting wear.', 2659.00, 10, 10),
('CHANEL LES BEIGES Healthy Glow Natural Eyeshadow Palette', 'With natural and elegant tones, this palette creates a warm and radiant look on the eyes.', 3000.00, 10, 10),
('REM BEAUTY Midnight Shadows babydoll', 'With six ultra-blendable matte and shimmer shades, it offers eye-catching makeup looks from day to night.', 1619.00, 10, 10),
('GIVENCHY Le 9 De Givenchy 9.1', 'With nine ultra-pigmented shades in matte, satin, and metallic textures, it provides natural and sophisticated eye makeup with 12-hour wear.', 3447.00, 10, 10),
('ANASTASIA BEVERLY HILLS Mini Loose Setting Powder', 'With its lightweight and silky texture, it sets makeup for a smooth, matte finish and enhances wear throughout the day.', 1189.00, 11, 15),
('HUDA BEAUTY Easy Bake Loose Ube Birthday Cake', 'With a fine, lightweight formula, it sets makeup while giving the skin a matte, smooth, and long-lasting finish.', 3939.00, 11, 10),
('HUDA BEAUTY Easy Bake Loose Coffee Cake', 'With a fine, lightweight formula, it sets makeup while giving the skin a matte, smooth, and long-lasting finish.', 3939.00, 11, 10),
('HUDA BEAUTY Easy Bake Loose Sugar Cookie', 'With a fine, lightweight formula, it sets makeup while giving the skin a matte, smooth, and long-lasting finish.', 3939.00, 11, 10),
('LANCÔME Long Time No Shine', 'With a light and fine texture, it absorbs excess oil, smooths the skin, and sets makeup while controlling shine all day long.', 3350.00, 11, 10),
('NARS Nars Light Compact Powder', 'It sets the makeup, enhancing its longevity while offering a natural glow and smooth finish with its fine texture.', 1330.00, 11, 10),
('DIOR Forever Cushion Powder 010', 'Enriched with water and violet extract, this powder sets makeup while providing a natural, matte, and radiant finish for the skin.', 2986.00, 11, 10),
('DIOR Forever Cushion Powder 020', 'Enriched with water and violet extract, this powder sets makeup while providing a natural, matte, and radiant finish for the skin.', 2986.00, 11, 10),
('DIOR Forever Cushion Powder 040', 'Enriched with water and violet extract, this powder sets makeup while providing a natural, matte, and radiant finish for the skin.', 2986.00, 11, 10),
('MAKE UP FOR EVER HD Skin Setting Powder', 'With 24-hour wear and an ultra-fine formula, it controls excess oil on the skin, providing a matte and smooth finish, blurs pores and fine lines, and delivers a natural finish even under flash photography.', 1309.00, 11, 10),
('TOO FACED Translucent Deep Born This Way', 'With its lightweight texture, it sets makeup, giving the skin a natural, radiant finish and blurring imperfections.', 2419.00, 11, 10),
('FENTY BEAUTY Pro Filt"r Mini Instant Retouch Banana', 'With its oil-free and lightweight formula, it blurs pores, evens out skin tone, controls shine, and enhances makeup wear.', 1009.00, 11, 10),
('FENTY BEAUTY Pro Filt"r Mini Instant Retouch Honey', 'With its oil-free and lightweight formula, it blurs pores, evens out skin tone, controls shine, and enhances makeup wear.', 1009.00, 11, 10),
('FENTY BEAUTY Pro Filt"r Mini Instant Retouch Butter', 'With its oil-free and lightweight formula, it blurs pores, evens out skin tone, controls shine, and enhances makeup wear.', 1009.00, 11, 10),
('LANCÔME Absolue Rose80 Body Lotion', 'With a formula containing 80% Absolue Rose Extract, Biotech Renewal Fractions™, and Pro-Xylane™, it tightens, smooths, and reduces moisture loss, providing a more youthful-looking skin.', 8250.00, 12, 15),
('RARE BEAUTY Find Comfort Hydrating Body Lotion', 'With a formula enriched with niacinamide, peach blossom, and ashwagandha extracts, it moisturizes, softens, and gives a natural glow to the skin for 24 hours.', 2059.00, 12, 15),
('FIRST AID BEAUTY KP Smoothing Body Lotion', 'With 10% lactic acid (AHA) in its formula, it reduces the rough skin appearance caused by keratosis pilaris while deeply moisturizing and soothing the skin with urea, colloidal oatmeal, and ceramides.', 2169.00, 12, 15),
('CHANEL N°5 Body Lotion', 'Enriched with rose and jasmine extracts, this lightweight lotion moisturizes the skin for 8 hours and leaves a delicate scent of the iconic N°5 perfume on the skin.', 2800.00, 12, 15),
('NARCISO RODRIGUEZ All of Me Body Lotion', '200ml. While moisturizing the skin, it leaves a delicate and lasting perfume scent.', 2970.00, 12, 15),
('DRUNK ELEPHANT Sili™ Whipped Body Lotion', '240ml. With a silky touch, it offers a velvety softness to your skin, revealing its natural radiance with deep hydration that lasts all day.', 2479.00, 12, 15),
('AUGUSTINUS BADER Body Lotion', '100ml. Intensely nourishes your skin, giving it a healthy and smooth appearance; each application offers a luxurious touch to your skin.', 4199.00, 12, 15),
('LA MER The Reparative Body Lotion', '160ml. It repairs and deeply moisturizes your skin. It provides softness with a delicate, rejuvenating effect, pampering your skin.', 7635.00, 12, 15),
('CHANEL COCO NOIR Body Lotion', '200ml. Deeply moisturizes your skin while leaving a sophisticated and lasting perfume note, offering a smooth touch to your skin.', 2800.00, 12, 15),
('SOL DE JANEIRO Rio Radiance Body Lotion', '200ml. While providing high sun protection, it deeply moisturizes your skin and illuminates it with a natural glow, allowing you to enjoy the sun with confidence.', 2969.00, 12, 15);




-- -- 6️⃣ Siparişler
-- INSERT INTO order_tbl (user_id, order_date, total) VALUES
-- (1, '2025-04-08', 1020.00),
-- (2, '2025-04-07', 40.00);

-- -- 7️⃣ Sipariş detayları
-- INSERT INTO order_detail (order_id, product_id, quantity, unit_price, total) VALUES
-- (1,1, 1, 1000.00, 1000.00),
-- (1,2, 1, 20.00, 20.00),
-- (1,2, 2, 20.00, 40.00);

-- -- 8️⃣ Sepet tablosu
-- INSERT INTO cart_tbl (user_id, product_id, quantity, unit_price, total) VALUES
-- (1,1, 1, 1000.00, 1000.00),
-- (1,3, 2, 15.00, 30.00);

-- -- 9️⃣ Ürün puanlama
-- INSERT INTO rate_tbl (user_id, product_id, rate) VALUES
-- (1,1, 4.5),
-- (1,2, 4.0);